//
// Created by Aditya Parmar on 03-01-2024.
//

#ifndef RUBIKS_CUBE_SOLVER1_RUBIKSCUBE3DARRAY_H
#define RUBIKS_CUBE_SOLVER1_RUBIKSCUBE3DARRAY_H


class RubiksCube3dArray {

};


#endif //RUBIKS_CUBE_SOLVER1_RUBIKSCUBE3DARRAY_H
